- spanish.html
Mofificaciones y mejoramientos extensos al text en Español.
Urgente que se pliquen estos cambios ya que lo que existe ahora esta muy mal escrito y deficiente.
todavia falta una pequeña parte del texto por corregir
> Mejoramiento de textos en Español

- package.json
- static/bp.json
- static/chains.json
- yarn.lock
> feat(bpjson) add bpjson files

- src/pages/index.js
- src/pages/styles.module.css
- Add class to input text and Textarea fields
1. yarn start
2. go to localhost:3000
3. scroll down to the contact us section and see the styles
> Input styles

- docusaurus.config.js
- package-lock.json
- package.json
- src/css/custom.css
- src/pages/index.js
- src/pages/services.js
- src/pages/styles.module.css
- Remove lazy imports and suspense
- Rewrite container class
1. yarn start
1. go to localhost:3000
1. navigate in the app
> Remove suspense

- docusaurus.config.js
> fix(config): add google analytics tracking code

- src/pages/block-producer.js
- static/jungle3.json
> fix(bpjson): update bpjson website urls

- src/pages/about.js
> Update about.js 1 (text)

- src/pages/services.js
> Update services.js 1 (texts)

- src/pages/index.js
> Update index.js 1 (texts)

- src/pages/about.js
- src/pages/components/Accordion/index.js
- src/pages/components/ContactUs/index.js
- src/pages/index.js
- src/pages/services.js
- src/pages/styles.module.css
- src/theme/Navbar.js
- Add links to buttons page
- Fix comments UI issues
- Fix navbar issue
- add picture size according to responsive screen
1. yarn start
2. go to localhost:3000
3. see home, services and industries pages
> Fix comments ui iisues

- blog/2020-04-15-what-is-blockchain.md
> Updated links

- .gitignore
- docusaurus.config.js
- package.json
> Initial config

- src/pages/about.js
- src/pages/block-producer.js
- src/pages/components/Accordion/index.js
- src/pages/industries.js
- src/pages/projects.js
- src/pages/services.js
- src/pages/styles.module.css
- src/pages/styles.module.js
- src/pages/thank-you.js
- src/theme/index.js
- src/theme/palette.js
- src/theme/typography.js
#93 
1. Create and apply themes
1. Create file to management styles
> Apply material IU and themes

- src/pages/index.js
Fix broken link based on issue #181
1. Click the link
> Fix broken link

- src/css/custom.css
- src/pages/block-producer.js
- src/pages/index.js
- src/pages/industries.js
- src/pages/services.js
- src/pages/team.js
- src/pages/the-company.js
- src/theme/Navbar.js
closes #200 #207
- make visual adjustment in mobile version
- yarn start
- go to http://localhost:3000/ in mobile version
> refactor: visual adjustment in mobile version

- src/pages/components/AccordionComp/index.js
- src/pages/industries.js
- src/pages/services.js
- add an accordion component 
- implement accordion in required pages
> feat: add accordion component

- src/pages/block-producer.js
- src/pages/components/ContactUsBanner/index.js
- src/pages/components/WeAreOneGroup/index.js
- src/pages/index.js
- src/pages/industries.js
- src/pages/services.js
- src/pages/the-company.js
What does this PR do?
- add `we are one group` component
- add `contact us banner` component
- improve code style in home page
> feat: add generic components

- src/pages/Animations/Games.js
- src/pages/Animations/Logistic.js
- src/pages/Animations/Payments.js
- src/pages/components/AccordionComp/index.js
- src/pages/components/MetaTags/index.js
- src/pages/team.js
- src/theme/Footer.js
- resolve comments in the Pull request
> refactor: improve code style

- static/bp.json
> update bpjson info

- static/bp.json
> fix(bpjson): update info

- src/pages/block-producer.js
- src/pages/projects.js
- static/bp.json
- static/jungle3.json
> fix(dashboard): update dashboard url

- static/jungle3.json
- static/wax-testnet.json
- static/wax.json
Wax account names need to be 12 characters
> Fix wax account names

- src/pages/team.js
Updated my twitter handle.
No issue.
No test.
> Twitter handle

- static/bp.json
- static/chains.json
- static/jungle4.json
- static/proton-testnet.json
- static/proton.json
- static/telos-testnet.json
- static/telos.json
- static/wax-testnet.json
- static/wax.json
> fix(bpjson): update block producer info

- README.md
- src/pages/block-producer.js
- src/pages/components/AdditionalResources/index.js
- src/pages/index.js
- src/pages/projects.js
- src/pages/services.js
- src/pages/the-company.js
- Resolves #465 
- Resolves #466 
1. Run `yarn build`
2. Run `yarn start`
3. Go to `localhost:3000`
4. Go to Website Pages
> feat(src): add new content

- src/theme/Navbar.js
> fix(components): fixed do-you-need-blockchain ref page

- src/pages/team.js
- static/bp.json
> update texts team
